language: python
sudo: required
dist: bionic
python: 3.6
branches:
  except:
    - /^untagged/
    - /\.dev[0-9]+$/
virtualenv:
  system_site_packages: true
before_install:
- sudo apt-get -qq update
- |
  sudo apt-get install -y \
      rpm fakeroot jq python-all python3-all python-setuptools python3-setuptools debhelper
install:
- pip install -r requirements_setup.txt -r requirements_test.txt
- pip3 install -r requirements_setup.txt -r requirements_test.txt
script:
- export VERSION=${TRAVIS_TAG:-$(<version.txt).dev${TRAVIS_BUILD_NUMBER}}
- export DVERSION=$(echo ${VERSION} | sed -e 's/\.dev/~dev/')
- python setup.py test build sdist bdist_wheel bdist
- ls -al dist/
- pip install dist/gcg-*.whl
- python setup.py --command-packages=stdeb.command sdist_dsc
- gcg -O deb -n gcg -D unstable -c "${VERSION}" -o deb_dist/gcg-${DVERSION}/debian/changelog
- echo "3.0 (native)" > deb_dist/gcg-${DVERSION}/debian/source/format
- |
  pushd deb_dist/gcg-${DVERSION} && patch -p0 << EOF
  --- debian/rules.orig   2019-07-14 15:59:44.076304052 +0000
  +++ debian/rules        2019-07-14 16:01:55.485231388 +0000
  @@ -21,9 +21,10 @@
  
   
   override_dh_auto_install:
  -       python setup.py install --force --root=debian/python-gcg --no-compile -O0 --install-layout=deb --prefix=/usr --install-scripts=/trash
  +       python setup.py install --force --root=debian/python-gcg --no-compile -O0 --install-layout=deb --prefix=/usr
  +       mv debian/python-gcg/usr/bin/gcg debian/python-gcg/usr/bin/gcg-2
          python3 setup.py install --force --root=debian/python3-gcg --no-compile -O0 --install-layout=deb --prefix=/usr 
  -       rm -rf debian/python-gcg/trash
  +       mv debian/python-gcg/usr/bin/gcg debian/python-gcg/usr/bin/gcg-3
   
   
   override_dh_python2:
  EOF
- rm -f deb_dist/*.dsc deb_dist/*.tar.* deb_dist/*.buildinfo deb_dist/*.changes
- pushd deb_dist/gcg-${DVERSION} && dpkg-source -b . ; popd
- sed -e "s/_VERSION_/${VERSION}/g" < gcg.spec.in > gcg.spec
- gcg -O rpm >> gcg.spec
- cp .rpmmacros ~/
- rpmbuild -ba gcg.spec --nodeps --with python3 --define "_topdir ${PWD}/rpm_dist" --define "_sourcedir ${PWD}/dist"
- rpm -qlpi --requires --verbose rpm_dist/RPMS/*/*.rpm rpm_dist/SRPMS/*.rpm
before_deploy:
- ls -al ; pwd
- find dist -ls
- find deb_dist -ls
- find rpm_dist -ls
- |
  if [[ -n "$TRAVIS_TAG" ]] && [[ "${TRAVIS_TAG}" != "$(<version.txt)" ]]; then
      >&2 echo "ERROR: You have marked a release by applying a Git tag and your version.txt doesn't match it"
      >&2 echo "Tip: Don't tag if you want to deploy only to test.pypi.org"
      false
  fi
before_deploy:
  - git config --local user.name "$GH_USER"
  - git config --local user.email "$GH_MAIL"
  - git tag $VERSION
deploy:
  provider: releases
  api_key: $GH_APIKEY
  file_glob: true
  file:
    - dist/gcg-${VERSION}.tar.gz
    - dist/*.whl
    - rpm_dist/**/*.rpm
    - deb_dist/**/*.deb
    - deb_dist/**/*.dsc
    - deb_dist/**/*.tar.*
  skip_cleanup: true
  on:
    repo: felfert/git-changelog-generator
    branch: python3
