language: python
sudo: required
dist: bionic
python: 3.6
branches:
  except:
    - /^untagged/
    - /\.dev$/
virtualenv:
  system_site_packages: true
before_install:
- sudo apt-get -qq update
- |
  sudo apt-get install -y \
      rpm fakeroot jq python-all python3-all python-setuptools python3-setuptools debhelper
- curl -L "http://download.opensuse.org/repositories/home:/felfert/xUbuntu_18.04/Release.key"
  | sudo apt-key add
- echo "deb http://download.opensuse.org/repositories/home:/felfert/xUbuntu_18.04 ./"
  | sudo tee /etc/apt/sources.list.d/felfert.list ;
- sudo apt-get update -q
- sudo apt-get install -y python-rpm-macros
install:
- pip install -r requirements_setup.txt -r requirements_test.txt
script:
- export VERSION=${TRAVIS_TAG:-$(<version.txt).dev${TRAVIS_BUILD_NUMBER}}
- python setup.py test build sdist bdist_wheel bdist
- ls -al dist/
- pip install dist/gcg-*.whl
- python setup.py --command-packages=stdeb.command sdist_dsc
- sed -e "s/_VERSION_/${VERSION}/g" < gcg.spec.in > gcg.spec
- gcg -O rpm >> gcg.spec
- mkdir -p rpm_dist
- rpmbuild -bs gcg.spec  --nodeps --define "_topdir ${PWD}/rpm_dist" --define "_sourcedir ${PWD}/dist" --define "_buildshell /bin/bash"
- rpm -qlpi --requires --verbose rpm_dist/RPMS/*/*.rpm rpm_dist/SRPMS/*.rpm
before_deploy:
- ls -al; pwd; find dist deb_dist -ls
- |
  if [[ -n "$TRAVIS_TAG" ]] && [[ "${TRAVIS_TAG}" != "$(<version.txt)" ]]; then
      >&2 echo "ERROR: You have marked a release by applying a Git tag and your version.txt doesn't match it"
      >&2 echo "Tip: Don't tag if you want to deploy only to test.pypi.org"
      false
  fi
before_deploy:
  - git config --local user.name "$GH_USER"
  - git config --local user.email "$GH_MAIL"
  - git tag $VERSION
deploy:
  provider: releases
  api_key: $GH_APIKEY
  file_glob: true
  file:
    - dist/*.tar.gz
    - dist/*.whl
    - rpm_dist/**/*.rpm
    - deb_dist/**/*.deb
    - deb_dist/**/*.dsc
    - deb_dist/**/*.tar.*
  skip_cleanup: true
  on:
    repo: felfert/git-changelog-generator
    branch: python3
