language: python
sudo: required
dist: bionic
python: 3.6
git:
  depth: false
branches:
  except:
    - /^untagged/
    - /\.dev[0-9]+$/
virtualenv:
  system_site_packages: true
before_install:
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch --tags
- sudo apt-get -qq update
- |
  sudo apt-get install -y \
      rpm fakeroot jq python-all python3-all python-setuptools python3-setuptools debhelper \
      python-pytest-runner python3-pytest-runner
install:
- pip install -r requirements_setup.txt -r requirements_test.txt
- pip3 install -r requirements_setup.txt -r requirements_test.txt
script:
- export VERSION=${TRAVIS_TAG:-$(<version.txt).dev${TRAVIS_BUILD_NUMBER}}
- python setup.py test bdist_wheel
- pip install dist/gcg-*.whl
- gcg -O deb -n gcg -D unstable -c "${VERSION}" -o debian/changelog
- sed -e  's/^$/./' -e 's/^/ /' LICENSE >> debian/copyright
- python setup.py sdist
- mkdir -p deb_dist
- tar xzCf deb_dist dist/gcg-${VERSION}.tar.gz
- pushd deb_dist/gcg-${VERSION} && dpkg-source -b . && popd
- pushd deb_dist/gcg-${VERSION} && dpkg-buildpackage -A --no-sign && popd
- sed -e "s/_VERSION_/${VERSION}/g" < gcg.spec.in > gcg.spec
- gcg -O rpm >> gcg.spec
- cp .rpmmacros ~/
- rpmbuild -ba gcg.spec --nodeps --with python3 --define "_topdir ${PWD}/rpm_dist" --define "_sourcedir ${PWD}/dist"
- rpm -qlpi --requires --verbose rpm_dist/RPMS/*/*.rpm rpm_dist/SRPMS/*.rpm
before_deploy:
- ls -al ; pwd
- find dist -ls
- find deb_dist -ls
- find rpm_dist -ls
- |
  if [[ -n "$TRAVIS_TAG" ]] && [[ "${TRAVIS_TAG}" != "$(<version.txt)" ]]; then
      >&2 echo "ERROR: You have marked a release by applying a Git tag and your version.txt doesn't match it"
      >&2 echo "Tip: Don't tag if you want to deploy only to test.pypi.org"
      false
  fi
before_deploy:
  - git config --local user.name "$GH_USER"
  - git config --local user.email "$GH_MAIL"
  - git tag $VERSION
deploy:
  provider: releases
  api_key: $GH_APIKEY
  file_glob: true
  file:
    - dist/gcg-${VERSION}.tar.gz
    - dist/*.whl
    - rpm_dist/**/*.rpm
    - deb_dist/*.deb
    - deb_dist/*.dsc
    - deb_dist/*.tar.*
  skip_cleanup: true
  on:
    repo: felfert/git-changelog-generator
